#!/bin/zsh 

if [[ -z $STOW_FOLDERS ]] then
    STOW_FOLDERS="bin,zsh,nvim,tmux,alacritty"
fi

if [[ -z $DOTFILES ]] then
    DOTFILES=$HOME/.dotfiles
fi

DOTFILES=$DOTFILES STOW_FOLDERS=$STOW_FOLDERS pushd $DOTFILES

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -R $folder
done

popd
